/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/Bar/index.vue')['default']
    BoardCard: typeof import('./src/components/BoardCard/index.vue')['default']
    BoardPage: typeof import('./src/components/BoardPage/index.vue')['default']
    CardHeader: typeof import('./src/components/CardHeader/index.vue')['default']
    Computer: typeof import('./src/components/Computer/index.vue')['default']
    CpuCard: typeof import('./src/components/CpuCard/index.vue')['default']
    DeviceSpecsLite: typeof import('./src/components/DeviceSpecsLite/index.vue')['default']
    DiskCard: typeof import('./src/components/DiskCard/index.vue')['default']
    GpuCard: typeof import('./src/components/GpuCard/index.vue')['default']
    GraphicsPage: typeof import('./src/components/GraphicsPage/index.vue')['default']
    LabelIcon: typeof import('./src/components/LabelIcon/index.vue')['default']
    MemoCard: typeof import('./src/components/MemoCard/index.vue')['default']
    MemoryPage: typeof import('./src/components/MemoryPage/index.vue')['default']
    OptionCard: typeof import('./src/components/OptionCard/index.vue')['default']
    Processor: typeof import('./src/components/Processor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateBlock: typeof import('./src/components/common/StateBlock.vue')['default']
    StoragePage: typeof import('./src/components/StoragePage/index.vue')['default']
    SuperLiteMonitorView: typeof import('./src/components/Watch/SuperLiteMonitorView.vue')['default']
    SystemOverview: typeof import('./src/components/SystemOverview/index.vue')['default']
    Watch: typeof import('./src/components/Watch/index.vue')['default']
    WatchRow: typeof import('./src/components/Watch/WatchRow/index.vue')['default']
  }
}
