/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/Bar/index.vue')['default']
    BoardCard: typeof import('./src/components/BoardCard/index.vue')['default']
    Computer: typeof import('./src/components/Computer/index.vue')['default']
    CpuCard: typeof import('./src/components/CpuCard/index.vue')['default']
    DiskCard: typeof import('./src/components/DiskCard/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GpuCard: typeof import('./src/components/GpuCard/index.vue')['default']
    LabelIcon: typeof import('./src/components/LabelIcon/index.vue')['default']
    MemoCard: typeof import('./src/components/MemoCard/index.vue')['default']
    OptionCard: typeof import('./src/components/OptionCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Watch: typeof import('./src/components/Watch/index.vue')['default']
    WatchRow: typeof import('./src/components/Watch/WatchRow/index.vue')['default']
  }
}
