/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/Bar/index.vue')['default']
    BoardPage: typeof import('./src/components/BoardPage/index.vue')['default']
    Computer: typeof import('./src/components/Computer/index.vue')['default']
    DeviceSpecsLite: typeof import('./src/components/DeviceSpecsLite/index.vue')['default']
    GraphicsPage: typeof import('./src/components/GraphicsPage/index.vue')['default']
    MemoryPage: typeof import('./src/components/MemoryPage/index.vue')['default']
    MonitoringDashboard: typeof import('./src/components/MonitoringDashboard/index.vue')['default']
    Processor: typeof import('./src/components/Processor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateBlock: typeof import('./src/components/common/StateBlock.vue')['default']
    StoragePage: typeof import('./src/components/StoragePage/index.vue')['default']
    SuperLiteMonitorView: typeof import('./src/components/Watch/SuperLiteMonitorView.vue')['default']
    ThemeControl: typeof import('./src/components/common/ThemeControl.vue')['default']
    Watch: typeof import('./src/components/Watch/index.vue')['default']
    WatchRow: typeof import('./src/components/Watch/WatchRow/index.vue')['default']
  }
}
