const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

function readProjectFile(relativePath) {
  return fs.readFileSync(path.join(__dirname, '..', relativePath), 'utf8')
}

test('interactive page navigation exposes selected state to assistive technology', () => {
  const app = readProjectFile('src/App.vue')
  const watch = readProjectFile('src/components/Watch/index.vue')
  const board = readProjectFile('src/components/BoardPage/index.vue')
  const dashboard = readProjectFile('src/components/MonitoringDashboard/index.vue')

  assert.match(app, /:aria-current="selectedSection === item\.id \? 'page' : undefined"/)
  assert.match(app, /已打开\{\{ headerMeta\.title \}\}页面/)
  assert.match(app, /aria-live="polite" aria-atomic="true"/)
  assert.match(app, /:aria-expanded="sensorMenuOpen"/)
  assert.match(app, /aria-controls="sensor-menu-popover"/)
  assert.match(app, /id="sensor-menu-popover"[\s\S]*role="group"[\s\S]*aria-label="硬件传感器控制"/)
  assert.match(app, /const sensorMenuTriggerRef = ref<HTMLButtonElement \| null>\(null\)/)
  assert.match(app, /function closeSensorMenuAndRestoreFocus\(\)[\s\S]*sensorMenuTriggerRef\.value\?\.focus\(\)/)
  assert.match(app, /@keydown\.esc\.stop="closeSensorMenuAndRestoreFocus"/)
  assert.match(app, /sensor-menu-popover__message" role="status" aria-live="polite"/)
  assert.match(app, /const sensorAuthorizationDialogRef = ref<HTMLElement \| null>\(null\)/)
  assert.match(app, /const sensorAuthorizationReturnFocus = ref<HTMLElement \| null>\(null\)/)
  assert.match(app, /watch\(sensorAuthorizationPromptVisible,[\s\S]*sensorAuthorizationDialogRef\.value\?\.focus\(\)/)
  assert.match(app, /document\.activeElement instanceof HTMLElement/)
  assert.match(app, /returnFocus\?\.isConnected[\s\S]*returnFocus\.focus\(\)/)
  assert.match(app, /function trapSensorAuthorizationFocus\(event: KeyboardEvent\)/)
  assert.match(app, /querySelectorAll<HTMLButtonElement>\('button:not\(:disabled\)'\)/)
  assert.match(app, /@keydown\.tab="trapSensorAuthorizationFocus"/)
  assert.match(app, /function dismissSensorAuthorizationPrompt\(\) {[\s\S]*if \(sensorActionLoading\.value\) return[\s\S]*sensorAuthorizationPromptVisible\.value = false/)
  assert.match(app, /@keydown\.esc\.stop="dismissSensorAuthorizationPrompt"/)
  assert.match(app, /ref="sensorAuthorizationDialogRef"[\s\S]*role="dialog"[\s\S]*aria-modal="true"/)
  assert.match(app, /aria-labelledby="sensor-auth-dialog-title"/)
  assert.match(app, /aria-describedby="sensor-auth-dialog-description"/)
  assert.match(watch, /:aria-pressed="monitorMode === 'overview'"/)
  assert.match(watch, /:aria-pressed="monitorMode === 'cpu'"/)
  assert.match(watch, /:aria-pressed="monitorMode === 'gpu'"/)
  assert.match(watch, /role="group" aria-label="监控视图"/)
  assert.match(board, /role="tablist" aria-label="主板信息分类"/)
  assert.match(board, /role="tab"[\s\S]*:aria-selected="activeTab === tab\.id"/)
  assert.match(board, /:aria-controls="`board-panel-\$\{tab\.id\}`"/)
  assert.match(board, /:tabindex="activeTab === tab\.id \? 0 : -1"/)
  assert.match(board, /role="tabpanel"/)
  assert.match(board, /@keydown="handleBoardTabKeydown\(\$event, tab\.id\)"/)
  assert.match(board, /event\.key === 'ArrowRight'/)
  assert.match(board, /event\.key === 'Home'/)
  assert.match(dashboard, /:aria-pressed="monitoringRefreshSettings\.profile === profile\.id"/)
})
