const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

function readSource(relativePath) {
  return fs.readFileSync(path.join(__dirname, '..', relativePath), 'utf8')
}

test('plugin exposes a dedicated device specs entry that opens the standalone specs page', () => {
  const plugin = JSON.parse(readSource('plugin.json'))
  const preload = readSource('utools/preload.js')
  const windowService = readSource('utools/services/window.js')
  const entryBuilder = readSource('scripts/generate-utools-entry-pages.mjs')

  const feature = plugin.features.find((item) => item.code === 'hardwareSpecsLite')

  assert.ok(feature)
  assert.equal(feature.explain, '设备规格')
  assert.deepEqual(feature.cmds, ['设备规格', '电脑规格', '硬件规格'])
  assert.match(preload, /a_specs_lite:\s*{[\s\S]*prod:\s*{\s*height:\s*720,\s*width:\s*1080,\s*backgroundColor:\s*1\s*}/)
  assert.match(preload, /hardwareSpecsLite:\s*{[\s\S]*openPresetWindow\('a_specs_lite'\)/)
  assert.match(windowService, /if \(fileName === 'a_specs_lite'\) return 'deviceSpecs'/)
  assert.match(entryBuilder, /\['a_specs_lite',\s*'deviceSpecs'\]/)
})

test('App keeps device specs as a standalone page rather than another hardware-detail section', () => {
  const app = readSource('src/App.vue')

  assert.match(app, /const isDeviceSpecsPage = computed\(\(\) => currentPage\.value === 'deviceSpecs'\)/)
  assert.match(app, /v-else-if="isDeviceSpecsPage"[\s\S]*<DeviceSpecsLite :active="true"/)
  assert.doesNotMatch(app, /id:\s*'deviceSpecs',\s*label:\s*'设备规格'/)
  assert.doesNotMatch(app, /deviceSpecsRef/)
})

test('device specs uses only static or low-frequency hardware sources and progressively applies fields', () => {
  const source = readSource('src/components/DeviceSpecsLite/index.vue')
  const specsStore = readSource('src/composables/useDeviceSpecsHardwareData.ts')
  const systemService = readSource('utools/services/system.js')

  assert.match(source, /useDeviceSpecsHardwareData/)
  assert.match(source, /coreSpecCards/)
  assert.match(source, /label:\s*'处理器'/)
  assert.match(source, /label:\s*'显卡'/)
  assert.match(source, /label:\s*'内存'/)
  assert.match(source, /label:\s*'硬盘'/)
  assert.match(source, /label:\s*'网卡 \/ 本机 IP'/)
  assert.match(source, /label:\s*'主板 \/ 平台'/)
  assert.match(source, /本机 IPv4/)
  assert.match(source, /memoryManufacturers/)
  assert.match(source, /memoryPartNumbers/)
  assert.match(source, /`厂商 \$\{memoryManufacturers\.value\.join\(' \/ '\) \|\| unavailableFact\(\['memoryLayout'\]\)\}`/)
  assert.match(source, /function cleanVendorText\(value: unknown\)/)
  assert.match(source, /const vendor = cleanVendorText\(disk\.vendor\)/)
  assert.match(source, /primaryNetworkAdapter/)
  assert.match(source, /copyDeviceSpecsInfo/)
  assert.doesNotMatch(source, /StateBlock/)
  assert.doesNotMatch(source, /overviewHardwareStore/)

  assert.match(specsStore, /async function readAndApply<T>/)
  assert.match(specsStore, /pendingReads\.value \+= 1/)
  assert.match(specsStore, /setFetchState\(key, 'pending'\)/)
  assert.match(specsStore, /const value = await reader\(\)/)
  assert.match(specsStore, /setFetchState\(key, hasValue\(value\) \? 'ok' : 'missing'/)
  assert.match(specsStore, /setFetchState\(key, 'error', normalizeErrorMessage\(error\)\)/)
  assert.match(specsStore, /window\.services\.getCpuInfo\(/)
  assert.match(specsStore, /window\.services\.getStaticMemInfo\(/)
  assert.match(specsStore, /window\.services\.getStaticGpuInfo\(/)
  assert.match(specsStore, /window\.services\.getMemoryLayout\(/)
  assert.match(specsStore, /window\.services\.getDiskLayout\(/)
  assert.match(specsStore, /window\.services\.getNetworkAdapters\(/)
  assert.doesNotMatch(specsStore, /getCpuTemperature\(/)
  assert.doesNotMatch(specsStore, /getCpuFullLoad\(/)
  assert.doesNotMatch(specsStore, /getCpuCurrentSpeed\(/)
  assert.doesNotMatch(specsStore, /window\.services\.getGpuInfo\(/)
  assert.doesNotMatch(specsStore, /getTopProcesses\(/)
  assert.doesNotMatch(specsStore, /getNetworkStatus\(/)
  assert.doesNotMatch(specsStore, /getStorageIo\(/)
  assert.doesNotMatch(specsStore, /getTimeInfo\(/)

  assert.match(systemService, /getStaticMemInfo:/)
  assert.match(systemService, /getStaticGpuInfo:/)
  assert.match(systemService, /async function getNetworkAdapters\(\)/)
  assert.match(systemService, /SPEthernetDataType/)
  assert.match(systemService, /getNetworkAdapters,/)
  assert.match(systemService, /getMemoryLayout:[\s\S]*si\.memLayout\(\)/)
  assert.match(systemService, /getDiskLayout:[\s\S]*si\.diskLayout\(\)/)
  assert.doesNotMatch(systemService, /Win32_PhysicalMemory/)
  assert.doesNotMatch(systemService, /Win32_DiskDrive/)
  assert.match(systemService, /async function readStaticGpuInfo\(\)[\s\S]*?si\.graphics\(\)[\s\S]*?async function readGpuInfo/)
  assert.doesNotMatch(systemService, /async function readStaticGpuInfo\(\)[\s\S]*?OpenHardwareMonitor[\s\S]*?async function readGpuInfo/)
  assert.doesNotMatch(systemService, /async function readStaticGpuInfo\(\)[\s\S]*?powermetrics[\s\S]*?async function readGpuInfo/)
})

test('device specs keeps all six core items visible while grouping them for faster scanning', () => {
  const app = readSource('src/App.vue')
  const source = readSource('src/components/DeviceSpecsLite/index.vue')

  assert.match(app, /\.device-specs-stage,\s*\.monitor-dashboard-stage\s*{[\s\S]*grid-template-rows:\s*44px minmax\(0, 1fr\)/)
  assert.match(source, /label:\s*'核心计算'/)
  assert.match(source, /description:\s*'处理器、显卡与内存'/)
  assert.match(source, /label:\s*'设备与连接'/)
  assert.match(source, /description:\s*'硬盘、活动网卡与主板平台'/)
  assert.match(source, /\.core-spec-sections/)
  assert.match(source, /\.core-spec-grid\s*{[\s\S]*grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\)/)
  assert.match(source, /\.core-spec-card,\s*\.secondary-spec-panel\s*{[\s\S]*background:\s*var\(--card-background\)/)
  assert.doesNotMatch(source, /\.core-spec-card::before/)
  assert.match(source, /\.secondary-spec-panel__head/)
  assert.match(source, /核心硬件优先，次要信息保持低视觉权重/)
  assert.match(source, /@media \(max-width: 900px\)[\s\S]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/)
})

test('device specs distinguishes loading, missing, unsupported, and failed fields without noisy ready badges', () => {
  const source = readSource('src/components/DeviceSpecsLite/index.vue')
  const store = readSource('src/composables/useDeviceSpecsHardwareData.ts')

  assert.match(store, /type DeviceSpecsFetchStatus = 'pending' \| 'ok' \| 'missing' \| 'error'/)
  assert.match(store, /const fetchState = reactive/)
  assert.match(source, /case 'pending': return '读取中…'/)
  assert.match(source, /case 'missing': return '系统未提供'/)
  assert.match(source, /case 'unsupported': return '当前平台不支持'/)
  assert.match(source, /case 'error': return '读取失败'/)
  assert.match(source, /v-if="card\.availability !== 'ready'"/)
  assert.match(source, /核心项 \{\{ identifiedCoreCount \}\}\/6/)
  assert.match(source, /`厂商 \$\{memoryManufacturers\.value\.join\(' \/ '\) \|\| unavailableFact\(\['memoryLayout'\]\)\}`/)
  assert.match(source, /`厂商 \$\{vendor \|\| unavailableFact\(\['diskLayout'\]\)\}`/)
})

test('device specs resolves the active hardware adapter by interface and keeps its local IPv4 visible', () => {
  const source = readSource('src/components/DeviceSpecsLite/index.vue')

  assert.match(source, /networkAdapters\.value\.find\(\(item\) => item\.default\)/)
  assert.match(source, /networkAdapters\.value\.find\(\(item\) => item\.operstate === 'up' && Boolean\(item\.ip4\)\)/)
  assert.match(source, /const vendor = cleanText\(adapter\.vendor\)/)
  assert.match(source, /const model = cleanText\(adapter\.model\)/)
  assert.match(source, /`本机 IPv4 \$\{cleanText\(adapter\?\.ip4\)\}`/)
})
