const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

function readSource(relativePath) {
  return fs.readFileSync(path.join(__dirname, '..', relativePath), 'utf8')
}

test('monitoring keeps per-source success and failure state instead of treating a partial refresh as fully current', () => {
  const store = readSource('src/composables/useMonitorDashboardData.ts')

  assert.match(store, /export type MonitorTelemetryKey/)
  assert.match(store, /const telemetryStatus = reactive<Record<MonitorTelemetryKey, MonitorTelemetryStatus>>/)
  assert.match(store, /function updateTelemetryStatus\(/)
  assert.match(store, /status\.lastSuccessAt = completedAt/)
  assert.match(store, /status\.error = normalizeErrorMessage\(result\.reason\)/)
  assert.match(store, /function summarizeRefreshResults\(/)
  assert.match(store, /Object\.keys\(telemetryStatus\) as MonitorTelemetryKey\[\]/)
  assert.match(store, /if \(successfulKeys\.length\) lastSyncedAt\.value = completedAt/)
  assert.match(store, /return \{ failedKeys, successfulKeys \}/)
  assert.match(store, /let refreshInFlightIsForced = false/)
  assert.match(store, /let queuedForceRefresh: Promise<MonitorRefreshResult> \| undefined/)
  assert.match(store, /if \(!force \|\| refreshInFlightIsForced\) return refreshInFlight/)
  assert.match(store, /queuedForceRefresh = refreshInFlight[\s\S]*\.then\(\(\) => refreshMonitorMetrics\(true\)\)/)
  assert.match(store, /function scheduleNextPoll\(\)[\s\S]*try \{[\s\S]*await refreshMonitorMetrics\(\)[\s\S]*catch \{[\s\S]*lastError\.value = '监控轮询'[\s\S]*finally \{[\s\S]*scheduleNextPoll\(\)/)
})

test('monitoring dashboard explains stale cards and reports manual refresh results', () => {
  const dashboard = readSource('src/components/MonitoringDashboard/index.vue')

  assert.match(dashboard, /function telemetryDescription\(/)
  assert.match(dashboard, /function telemetryIsStale\(/)
  assert.match(dashboard, /return Boolean\(status\.error && status\.lastSuccessAt\)/)
  assert.match(dashboard, /读取失败 · 上次成功/)
  assert.match(dashboard, /monitor-metric-card--stale/)
  assert.match(dashboard, /monitor-live-card--stale/)
  assert.match(dashboard, /const hasMemoryTelemetry = computed/)
  assert.match(dashboard, /暂未提供处理器温度读数/)
  assert.match(dashboard, /当前显卡未提供温度读数/)
  assert.match(dashboard, /未检测到图形处理器/)
  assert.match(dashboard, /const processEmptyMessage = computed/)
  assert.match(dashboard, /暂未检测到占用较高的进程/)
  assert.match(dashboard, /尚无成功数据/)
  assert.match(dashboard, /monitor-dashboard-kicker__pulse--warning/)
  assert.match(dashboard, /\.monitor-toolbar__right \{[\s\S]*flex-wrap: wrap/)
  assert.match(dashboard, /\.monitor-toolbar__synced \{[\s\S]*white-space: nowrap/)
  assert.match(dashboard, /已刷新；\$\{result\.failedKeys\.length\} 项暂未更新/)
  assert.match(dashboard, /监控数据已更新/)
  assert.match(dashboard, /刷新设置保存失败，请重试/)
  assert.match(dashboard, /后台降频设置保存失败，请重试/)
  assert.match(dashboard, /:aria-busy="settingsPending"/)
  assert.match(dashboard, /class="monitor-refresh-button"[\s\S]*:aria-busy="refreshing"/)
  assert.match(dashboard, /:aria-busy="floatingLaunchMode === 'standard'"/)
  assert.match(dashboard, /:aria-busy="floatingLaunchMode === 'super-lite'"/)
})
